(() => {
  const menu = document.createElement('div'); menu.className='abf-context-menu'; menu.hidden=true; document.body.append(menu);
  let selected = null; let holdTimer = null; let holdStart = null; let longOpened = false;
  const escapeHtml = text => String(text).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  function itemFrom(target){const file=target.closest('[data-file]');if(file)return {kind:'file',id:file.dataset.file};const folder=target.closest('.folder-card[data-folder],.tree-item[data-folder]');return folder?{kind:'folder',id:folder.dataset.folder}:null;}
  function show(x,y,item){selected=item;const entry=item.kind==='file'?data.files.find(x=>x.id===item.id):data.folders.find(x=>x.id===item.id);if(!entry)return;menu.innerHTML=`<button data-action="open">↗ Open</button><button data-action="rename">✎ Rename</button><button data-action="move">↪ Move</button><hr /><button class="danger" data-action="delete">⌫ Delete</button>`;menu.hidden=false;const width=175,height=160;menu.style.left=Math.max(8,Math.min(x,window.innerWidth-width-8))+'px';menu.style.top=Math.max(8,Math.min(y,window.innerHeight-height-8))+'px';}
  function hide(){menu.hidden=true;selected=null;}
  function open(){if(selected.kind==='file'){state.selected=selected.id;render();}else{state.folder=selected.id;state.library='all';render();}hide();}
  function rename(){const entry=selected.kind==='file'?data.files.find(x=>x.id===selected.id):data.folders.find(x=>x.id===selected.id);const value=prompt(`Rename ${selected.kind}`,entry.name);if(value&&value.trim()){entry.name=value.trim();if(selected.kind==='file')entry.modified=new Date().toISOString();save();render();}hide();}
  function move(){const entry=selected.kind==='file'?data.files.find(x=>x.id===selected.id):data.folders.find(x=>x.id===selected.id);let choices=data.folders;if(selected.kind==='folder'){const blocked=descendants(entry.id);choices=choices.filter(folder=>!blocked.includes(folder.id));}const list=['Unfiled / top level',...choices.map(folder=>folder.name)];const answer=prompt(`Move ${entry.name} to:\n${list.map((name,index)=>`${index}: ${name}`).join('\n')}`);const choice=Number(answer);if(Number.isInteger(choice)&&choice>=0&&choice<list.length){if(selected.kind==='file')entry.folder=choice?choices[choice-1].id:null;else entry.parent=choice?choices[choice-1].id:null;if(selected.kind==='file')entry.modified=new Date().toISOString();save();render();}hide();}
  function remove(){if(selected.kind==='file')window.ABFTrash?.deleteFile(selected.id);else window.ABFTrash?.deleteFolder(selected.id);hide();}
  menu.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(!action)return;({open,rename,move,delete:remove})[action]();});
  document.addEventListener('contextmenu',event=>{const item=itemFrom(event.target);if(!item)return;event.preventDefault();show(event.clientX,event.clientY,item);});
  document.addEventListener('pointerdown',event=>{const item=itemFrom(event.target);if(!item||event.pointerType==='mouse')return;holdStart={x:event.clientX,y:event.clientY};holdTimer=setTimeout(()=>{show(event.clientX,event.clientY,item);navigator.vibrate?.(20);holdTimer=null;longOpened=true;},550);});
  document.addEventListener('pointermove',event=>{if(holdTimer&&holdStart&&Math.hypot(event.clientX-holdStart.x,event.clientY-holdStart.y)>12){clearTimeout(holdTimer);holdTimer=null;}});
  document.addEventListener('pointerup',()=>{if(holdTimer){clearTimeout(holdTimer);holdTimer=null;}});document.addEventListener('pointercancel',()=>{if(holdTimer){clearTimeout(holdTimer);holdTimer=null;}});
  document.addEventListener('click',event=>{if(!longOpened)return;longOpened=false;if(!event.target.closest('.abf-context-menu')){event.preventDefault();event.stopImmediatePropagation();}},true);
  document.addEventListener('click',event=>{if(!event.target.closest('.abf-context-menu'))hide();});window.addEventListener('resize',hide);window.addEventListener('scroll',hide,true);
})();
