(() => {
  const prefKey = 'abf-settings-v1';
  const defaults = { name:'Ashish', email:'', reminder:false, panels:{ files:{apps:false,browser:false}, apps:{files:false,browser:false}, browser:{files:false,apps:false} } };
  let prefs = JSON.parse(localStorage.getItem(prefKey) || JSON.stringify(defaults));
  prefs.panels ||= defaults.panels;
  const shell = document.querySelector('.app-shell');
  const main = document.querySelector('.main');
  const topActions = document.querySelector('.top-actions');
  document.querySelector('#returnHome').insertAdjacentHTML('afterend', '<button class="return-home" id="settingsButton">⚙ Settings</button>');
  document.querySelector('.workspace-nav-divider').insertAdjacentHTML('beforebegin', '<div class="panel-extra" id="fileSideExtras"><div class="side-panel-label">OTHER SPACES</div></div>');
  document.querySelector('.app-side-panel').insertAdjacentHTML('beforeend', '<div class="panel-extra" id="appsSideExtras"><div class="side-panel-label">OTHER SPACES</div></div>');
  document.querySelector('.browser-side-panel').insertAdjacentHTML('beforeend', '<div class="panel-extra" id="browserSideExtras"><div class="side-panel-label">OTHER SPACES</div></div>');
  const panel = document.createElement('section');
  panel.className = 'settings-panel';
  panel.innerHTML = `<div class="eyebrow">ABF SETTINGS</div><h1>Settings</h1><p>Make ABF feel right for you.</p><section class="settings-section"><h2>General</h2><div class="settings-card"><div class="setting-row"><div><h3>Display name</h3><p>Used for your profile circle in ABF.</p></div><input id="displayName" type="text" maxlength="24" /></div><div class="setting-row"><div><h3>Email address</h3><p>Shown when you open your profile menu.</p></div><input id="emailAddress" type="text" inputmode="email" placeholder="you@example.com" maxlength="80" /></div><div class="setting-row"><div><h3>Organisation reminder</h3><p>Remember to tidy your files each week.</p></div><label class="switch"><input id="reminderToggle" type="checkbox" /><span></span></label></div></div></section><section class="settings-section"><h2>Left panel shortcuts</h2><div class="settings-card"><div class="setting-row panel-setting"><div><h3>Files Management</h3><p>Add spaces you want to reach from the files panel.</p></div><div class="panel-checks"><label><input type="checkbox" data-panel="files:apps" /> Apps</label><label><input type="checkbox" data-panel="files:browser" /> Browser</label></div></div><div class="setting-row panel-setting"><div><h3>Apps</h3><p>Add a shortcut to other ABF spaces.</p></div><div class="panel-checks"><label><input type="checkbox" data-panel="apps:files" /> Files</label><label><input type="checkbox" data-panel="apps:browser" /> Browser</label></div></div><div class="setting-row panel-setting"><div><h3>Browser</h3><p>Add a shortcut to other ABF spaces.</p></div><div class="panel-checks"><label><input type="checkbox" data-panel="browser:files" /> Files</label><label><input type="checkbox" data-panel="browser:apps" /> Apps</label></div></div></div><p class="settings-note">Shortcuts only appear in the panel you choose and can be changed anytime.</p></section><section class="settings-section"><h2>Storage</h2><div class="settings-card"><div class="setting-row"><div><h3>Your ABF data</h3><p>Folders, preferences, and installed app shortcuts are saved in this browser.</p></div></div></div></section>`;
  main.append(panel);
  function save(){localStorage.setItem(prefKey,JSON.stringify(prefs));}
  function avatar(){ const initials=(prefs.name || 'ABF').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase(); document.querySelectorAll('.avatar').forEach(x=>{if(x.id!=='quickBrowser')x.textContent=initials;}); }
  function route(label){return label==='Files'?'<button data-settings-go="files">⌑ <span>Files</span></button>':label==='Apps'?'<button data-settings-go="apps">▦ <span>Apps</span></button>':'<button data-settings-go="browser">◎ <span>Browser</span></button>';}
  function renderExtras(){ const maps=[['files','fileSideExtras',[['apps','Apps'],['browser','Browser']]],['apps','appsSideExtras',[['files','Files'],['browser','Browser']]],['browser','browserSideExtras',[['files','Files'],['apps','Apps']]]]; maps.forEach(([space,id,choices])=>{const el=document.querySelector('#'+id);const on=choices.filter(([x])=>prefs.panels[space][x]);el.innerHTML='<div class="side-panel-label">OTHER SPACES</div>'+on.map(([,label])=>route(label)).join('');el.style.display=on.length?'block':'none';}); document.querySelectorAll('[data-settings-go]').forEach(button=>button.onclick=()=>{const target=button.dataset.settingsGo;if(target==='files')document.querySelector('[data-library="all"]').click();else document.querySelector(`[data-workspace="${target}"]`).click();}); }
  function fill(){document.querySelector('#displayName').value=prefs.name;document.querySelector('#emailAddress').value=prefs.email || '';document.querySelector('#reminderToggle').checked=prefs.reminder;document.querySelectorAll('[data-panel]').forEach(input=>{const [space,item]=input.dataset.panel.split(':');input.checked=!!prefs.panels[space][item];});avatar();renderExtras();}
  function openSettings(){document.querySelector('.workspace-panel')?.classList.remove('is-open');document.querySelector('.home-panel')?.classList.remove('is-open');main.classList.remove('workspace-active','home-active');main.classList.add('settings-active');shell.classList.remove('home-mode','workspace-mode','apps-active','browser-active');shell.classList.add('settings-mode');panel.classList.add('is-open');fill();history.pushState({abfView:'settings'},'', '#settings');}
  function closeSettings(){main.classList.remove('settings-active');shell.classList.remove('settings-mode');panel.classList.remove('is-open');}
  document.querySelector('#settingsButton').onclick=openSettings;
  document.querySelector('#displayName').oninput=e=>{prefs.name=e.target.value.trim()||'ABF';save();avatar();};
  document.querySelector('#emailAddress').oninput=e=>{prefs.email=e.target.value.trim();save();};
  document.querySelector('#reminderToggle').onchange=e=>{prefs.reminder=e.target.checked;save();};
  document.querySelectorAll('[data-panel]').forEach(input=>input.onchange=e=>{const [space,item]=e.target.dataset.panel.split(':');prefs.panels[space][item]=e.target.checked;save();renderExtras();});
  document.querySelector('#returnHome').addEventListener('click',closeSettings); document.querySelector('#homeBrand').addEventListener('click',closeSettings);
  window.addEventListener('popstate',event=>{if(event.state?.abfView!=='settings')closeSettings();});
  fill();
})();
