(() => {
  const trashKey = 'abf-recently-deleted-v1';
  const maxAge = 30 * 24 * 60 * 60 * 1000;
  let deleted = JSON.parse(localStorage.getItem(trashKey) || '[]');
  const main = document.querySelector('.main');
  document.querySelector('.workspace-nav-divider').insertAdjacentHTML('beforebegin', '<button class="trash-link" id="openTrash">♲ <span>Recently deleted</span><b id="trashCount">0</b></button>');
  const panel = document.createElement('section'); panel.className='trash-panel'; panel.innerHTML='<div id="trashContent"></div>'; main.append(panel);
  function persist(){localStorage.setItem(trashKey,JSON.stringify(deleted));}
  function cleanup(){const now=Date.now();const before=deleted.length;deleted=deleted.filter(entry=>now-new Date(entry.deletedAt).getTime()<maxAge);if(before!==deleted.length)persist();}
  function daysLeft(entry){return Math.max(0,Math.ceil((maxAge-(Date.now()-new Date(entry.deletedAt).getTime()))/86400000));}
  function updateCount(){document.querySelector('#trashCount').textContent=deleted.length;}
  function draw(){cleanup();updateCount();const content=document.querySelector('#trashContent');if(!deleted.length){content.innerHTML='<div class="trash-head"><div><h1>Recently deleted</h1><p>Items stay here for 30 days before being permanently deleted.</p></div><button id="backToFiles">← Back to files</button></div><div class="trash-list"><div class="trash-empty"><div>♲</div><h2>Nothing deleted</h2><p>Deleted files and folders can be restored here for 30 days.</p></div></div>';document.querySelector('#backToFiles').onclick=close;return;}content.innerHTML=`<div class="trash-head"><div><h1>Recently deleted</h1><p>Restore anything before its 30-day window ends.</p></div><button id="backToFiles">← Back to files</button></div><div class="trash-list">${deleted.slice().sort((a,b)=>new Date(b.deletedAt)-new Date(a.deletedAt)).map(entry=>`<div class="trash-row"><div class="trash-row-icon">${entry.kind==='folder'?'⌑':'▧'}</div><div class="trash-row-info"><strong>${entry.kind==='folder'?entry.snapshot.folder.name:entry.snapshot.name}</strong><span>${entry.kind==='folder'?'Folder':'File'} · ${daysLeft(entry)} day${daysLeft(entry)===1?'':'s'} left</span></div><div class="trash-row-actions"><button data-restore="${entry.id}">Restore</button><button class="permanent" data-permanent="${entry.id}">Delete forever</button></div></div>`).join('')}</div><p class="trash-note">After 30 days, items are permanently deleted automatically.</p>`;document.querySelector('#backToFiles').onclick=close;content.querySelectorAll('[data-restore]').forEach(button=>button.onclick=()=>restore(button.dataset.restore));content.querySelectorAll('[data-permanent]').forEach(button=>button.onclick=()=>permanent(button.dataset.permanent));}
  function open(){cleanup();main.classList.add('trash-active');panel.classList.add('is-open');document.querySelector('#openTrash').classList.add('active');draw();}
  function close(){main.classList.remove('trash-active');panel.classList.remove('is-open');document.querySelector('#openTrash').classList.remove('active');}
  function move(entry){deleted.push(entry);persist();updateCount();}
  function requestDelete(attribute, id){const button=document.createElement('button');button.dataset[attribute]=id;button.hidden=true;document.body.append(button);button.click();button.remove();}
  window.ABFTrash={deleteFile:id=>requestDelete('deleteFile',id),deleteFolder:id=>requestDelete('deleteFolder',id)};
  function restore(id){const entry=deleted.find(x=>x.id===id);if(!entry)return;if(entry.kind==='file')data.files.push(entry.snapshot);else{data.folders.push(...entry.snapshot.folders);data.files.push(...entry.snapshot.files);}deleted=deleted.filter(x=>x.id!==id);persist();save();render();draw();}
  function permanent(id){if(!confirm('Permanently delete this item? This cannot be undone.'))return;deleted=deleted.filter(x=>x.id!==id);persist();draw();}
  document.addEventListener('click',event=>{const fileButton=event.target.closest('[data-delete-file]');const folderButton=event.target.closest('[data-delete-folder]');if(!fileButton&&!folderButton)return;event.preventDefault();event.stopImmediatePropagation();if(fileButton){const item=data.files.find(file=>file.id===fileButton.dataset.deleteFile);if(!item||!confirm('Move this file to Recently Deleted?'))return;move({id:'trash-'+Date.now()+'-'+item.id,kind:'file',snapshot:item,deletedAt:new Date().toISOString()});data.files=data.files.filter(file=>file.id!==item.id);if(state.selected===item.id)state.selected=null;save();render();return;}const folder=data.folders.find(item=>item.id===folderButton.dataset.deleteFolder);if(!folder||!confirm('Move this folder and its contents to Recently Deleted?'))return;const ids=descendants(folder.id);const snapshot={folder,folders:data.folders.filter(item=>ids.includes(item.id)),files:data.files.filter(item=>ids.includes(item.folder))};move({id:'trash-'+Date.now()+'-'+folder.id,kind:'folder',snapshot,deletedAt:new Date().toISOString()});data.folders=data.folders.filter(item=>!ids.includes(item.id));data.files=data.files.filter(item=>!ids.includes(item.folder));if(ids.includes(state.folder))state.folder=null;save();render();},true);
  document.querySelector('#openTrash').onclick=open;document.querySelectorAll('[data-library],[data-workspace],#settingsButton,#returnHome,#homeBrand').forEach(button=>button.addEventListener('click',close));
  cleanup();updateCount();setInterval(cleanup,60*60*1000);
})();
